# Generated by Django 4.0.4 on 2022-06-03 13:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('checkin', models.TimeField(auto_now_add=True, null=True)),
                ('checkout', models.TimeField(null=True)),
                ('time_worked', models.TimeField(null=True)),
                ('is_weekend', models.BooleanField(default=False)),
                ('employee_code', models.ForeignKey(db_column='employee_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employee', to_field='personal_code')),
            ],
        ),
    ]
