# Generated by Django 4.0.4 on 2022-06-01 20:29

from os import getenv

from django.contrib.auth import hashers
from django.db import migrations
from dotenv import load_dotenv

load_dotenv()


def default_account(apps, schema_editor):
    Account = apps.get_model("accounts", "Account")

    new_password = hashers.make_password(getenv("DEFAULT_ADM_PASSWORD"))

    default_data = {
        "email": getenv("DEFAULT_ADM_EMAIL"),
        "password": new_password,
    }

    Account.objects.create(**default_data)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [migrations.RunPython(default_account)]
